### PR TITLE
Update 'websockets' dependency to 8.x

### LINKED ISSUE #412: Update 'websockets' to 8.x
I realize that https://github.com/encode/uvicorn/pull/396 was done because the tests appear to be failing with `websockets>=8.0`, but that release also fixed a bunch of DeprecationWarnings that we've been seeing in [httpx builds on 3.8](https://travis-ci.org/encode/httpx/jobs/574949180).

Since it's only a `DeprecationWarning`, and only on 3.8 ([3.7 and below is fine](https://travis-ci.org/encode/httpx/jobs/574949179)), I definitely would agree that this is a low priority issue.

I dug into the tests to try and figure out what exactly was going wrong, but the `AttributeError`s I looked at looks like the main issue is two missing functions in [websockets_impl.py](https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/websockets/websockets_impl.py)

`15 AttributeError: 'Server' object has no attribute 'is_serving'` --> https://github.com/aaugustin/websockets/blob/8.0.2/src/websockets/server.py#L642-L668
` 9 AttributeError: 'WebSocketProtocol' object has no attribute 'transfer_data_task'` --> https://github.com/aaugustin/websockets/blob/8.0.2/src/websockets/protocol.py#L276-L313

### PR DESCRIPTION
**Pull request by lovelydinosaur**
Closes #412

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Okay, there's a call to be made here. `websockets 8.x` drops support for Python 3.5.

We need to figure out if we're okay with that.

There is an alternative, which would be to make it possible to install just the base `uvicorn` package without dependencies, and have our tests omit `websockets` for 3.5, but that's all a bit fiddly, and it's also a big jump (I'd kinda been planning something a bit similar to that for the 1.0 release.)

**Comment by lovelydinosaur** [comment]
I think we're gonna have to accept this, update to a 0.9 release, and document that if folks want Python 3.5 support, then they need to install 0.8.

3.5 EOL is [only a year away now](https://devguide.python.org/#status-of-python-branches), so that doesn't seem unreasonable. (Tho I know there's some install environments, eg. raspbian, glitch, that are still defaulting to 3.5 right now)

**Comment by StephenBrown2** [comment]
Woo! Thanks for this. I thought it would be far more involved than that. Now we just need a release (when it's time).

**Comment by lovelydinosaur** [comment]
Done. 0.9
